workflows:
  android-only:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Build Android Folder Once
        script: |
          if [ ! -d "android" ]; then
            flutter create . --platforms=android
          fi
          if ! grep -q "android.permission.INTERNET" android/app/src/main/AndroidManifest.xml; then
            sed -i '' 's/<application/<uses-permission android:name="android.permission.INTERNET" \/>\
          <application/' android/app/src/main/AndroidManifest.xml || sed -i 's/<application/<uses-permission android:name="android.permission.INTERNET" \/>\n<application/' android/app/src/main/AndroidManifest.xml
          fi
          flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
