workflows:
  android-only:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Build Android Folder Once
        script: |
          if [ ! -d "android" ]; then
            flutter create . --platforms=android
          fi
          flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
